#!/usr/bin/env bash

fatal() {
  echo "FATAL ERROR: $@"
  exit 1
}
trap 'sudo -k' EXIT

notify() {
  notify-send -t 2000 "$1" &
  aplay ./resources/sounds/tap.wav &
}

case $1 in 

status)
  STATUS=$(nmcli con show proton-us-udp | rg GENERAL.STATE --include-zero --count)

  echo $STATUS
 ;;

up)
  notify "Starting VPN connection"
  nmcli con up proton-us-udp
  ;;

down)
  notify "Stopping VPN connection"
  nmcli con down proton-us-udp 
  ;;
esac

exit 0
